version: '3.8'
services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  pma-test:
    image: phpmyadmin/phpmyadmin
    container_name: pma-test
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw
      - MEMORY_LIMIT=512M
      - UPLOAD_LIMIT=512M
    links:
      - mysql:mysql
    ports:
      - 8183:80

volumes:
  mysql_data:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mysql
  #   environment:
  #     DATABASE_HOST: mysql
  #     DATABASE_USER: root
  #     DATABASE_PASSWORD: my-secret-pw
  #     DATABASE_NAME: mydatabase
  #   ports:
  #     - "3000:3000"
